### ISSUE TITLE
Add archives link to Issues page

### ISSUE THREAD

**Issue by geealbers** [gettypubs/beyond-the-printed-page#17]
Add a link to the Archives from the Issues page. Perhaps in same format as Issues are listed?:

**Archives
[Chronological listing of posts back to 2012](http://gettypubs.github.io/beyond-the-printed-page/archive/)**

**Comment by egardner** [comment]
Added a basic link between these sections. I'm open to thoughts on how we want people to move between "issues" and "posts/archives".

**Comment by sgrimes12** [comment]
What do you think about changing "view post archive" to just "archives" or "view archives"  it took me a minute to understand this meant "posts"/ I thought it might have been a typo for "past" Also, thoughts on moving this down to the bottom of the page so that the emphasis is still on the issues and viewing the archive is another option?

**Comment by geealbers** [comment]
Yes, this doesn't really work for me either. Both because it's at the top, and it's in the same format as the tags. I feel like it should be at the bottom of the list of issues (which would be in reverse chronological order presumably) and treated in the same manner visually. Like it's Issue Zero. Maybe?

Issue 2
Title of Issue Two

Issue 1
Title of Issue One

Archives
Phrase about it being a complete archive of individual posts

**Comment by egardner** [comment]
I like the idea of handling this as "issue zero" – both conceptually and in
terms of design.

I was thinking it might be helpful to introduce breadcrumbs for issues &
posts, and this would allow everything to use the same scheme.

Issues > Issue 1 > etc...

Issues > Archive > etc...

**Comment by egardner** [comment]
Okay, as of a3ac9b9 there is now a breadcrumb secondary nav throughout the site.
I have erred on the side of making things really obvious and redundant, because I think it really improves on the site's usability to have a constant reminder of where you stand in the greater scheme of things.

I am open to suggestions on design, but all in all I think this is a good feature to include and will be especially helpful to new visitors.

**Comment by sgrimes12** [comment]
Secondary nav looks great!

**Comment by egardner** [comment]
I'm closing this now, but feel free to file a new issue relating to specific breadcrumb design/feature requests.
