### ISSUE TITLE
Add content to the directory 

### ISSUE THREAD

**Issue by sgrimes12** [gettypubs/beyond-the-printed-page#20]
Here is the website content to be added to the directory page. 

Check out what museums are publishing. Use the search and sort functions to browse the publications, see how museums present content and what digital formats they’re working with. We look forward to adding more publications and welcome peer participation.

**Comment by egardner** [comment]
Okay, just added this to the page. If you want to change text you can just go in and edit the `directory.html` file directly – look for the `<p>` tag near the top of the page, that's where intro content should live.

I made this a HTML page rather than a markdown one because the data table needs more markup in order to work but otherwise this page is the same as any other.
