### ISSUE TITLE
Add current Issue to homepage

### ISSUE THREAD

**Issue by geealbers** [gettypubs/beyond-the-printed-page#8]
Add title, issue number, and perhaps the short blurb for the current issue to the home page. 

I'm also wondering about the Issues and Archive navigations. If the current issue is accessible from the home page, the Issues and Archive pages are going to basically act as an Issues Archive and a Posts Archive. Not sure that makes sense. What do you think of combining them by including the issues list on the archive page?

**Comment by egardner** [comment]
Hmmm. Good question – I'm open to re-arranging navigation to something very different than what we have now, as our content starts to get organized. We could add a "topics" page somewhere to list all the tags too, etc.

**Comment by sgrimes12** [comment]
Check out this review journal for digital humanities projects: http://ride.i-d-e.de
Greg you've mentioned in the past that they could ease off on the word clouds but they have a nice way of utilizing their tags (http://ride.i-d-e.de/by-tag-2/) so instead of having a general "archives" section the tags serve as categories for past projects and articles (something we talked about). In addition, while they don't have much information right now, they're doing some interesting stuff with the "data" section to collect information and make it downloadable in XML files and present visualizations in the form of pretty simple charts, which sounds like a way we might want to present the bliki survey.

**Comment by egardner** [comment]
I think a lot of the same kinds of data manipulations are possible in Jekyll –  this is something I will explore this week when I upload the main resources chart. 

Also, interesting thing to note about tags – I can sort and organize them, but the sort behavior is case-sensitive (which means you'll see A, B, C, D... a, b, c, d). I'm trying to find a way to override that but it's proving to be surprisingly difficult.

**Comment by egardner** [comment]
As of afea7f0 the current issue shows up. I'm still styling but let me know if you want to see this organized differently.

**Comment by geealbers** [comment]
Nice. The site subtitle is more prominent now and I think maybe too much so. I've also been wondering what the wording should be. It's longer but maybe something like this? Not sure:

> The ideas, technology and people shaping digital publishing in art and museums today

And what do you think of "Current Issue | Spring 2015" on one line, and at the smaller size type? Feel like we could stand to consolidate some lines/elements.

**Comment by sgrimes12** [comment]
I like that tagline with a smaller font but could take or leave "today" in the wording.

**Comment by geealbers** [comment]
Good point about "today". Let's leave it off.

**Comment by sgrimes12** [comment]
What do you think about taking "the" off too:

Beyond the Printed Page
Ideas, technology, and people shaping digital publishing in art and museums 
OR
Beyond the Printed Page
Ideas, people, and tech shaping digital publishing in art and museums

**Comment by egardner** [comment]
Okay, I've added this content to the home page and made some more design tweaks. I can revise further but I'm going to switch gears and try to get the data working this afternoon.

**Comment by egardner** [comment]
I'm going to close this – feel free to open a new issue if there are specific design/content things that need to be added.
